### PR TITLE
update RightHandSideDigest

### PR DESCRIPTION
**Pull request by michaelficarra**
This is best reviewed in individual commits.

### CODE REVIEW

**Comment by rbuckton** [comment]
While I understand the higher density reasoning (in order to prevent collisions), why remove constraints from the digest created for a link? The goal was to be able to link to a specific RHS, and removing constraints removes identifying characteristics for the RHS.

**Comment by michaelficarra** [comment]
Dropping things from the digest comes from the usage in ecma262 where we omit flags, optionality, lookaheads, etc from RHSes when defining an SDO. We still want to have an identifier for that RHS so we can link it back properly. But I'm thinking now we could probably strip those things in ecmarkup before passing them to grammarkdown to get the digest we want. I'll see how difficult that will be for us.

**Comment by rbuckton** [comment]
> Dropping things from the digest comes from the usage in ecma262 where we omit flags, optionality, lookaheads, etc from RHSes when defining an SDO. We still want to have an identifier for that RHS so we can link it back properly. But I'm thinking now we could probably strip those things in ecmarkup before passing them to grammarkdown to get the digest we want. I'll see how difficult that will be for us.

Now that I have a better understanding of the problem you're trying to solve, I could see modifying the `grammarkdown` API to generate two RHS link IDs: a full link ID for explicit references, and a simplified link ID for SDOs. The full link ID is useful for linking via backreferences to specific locations in the document, so:

```grammarkdown
Prod1[Arg] :
  [+Arg] `keyword`? Prod2
  [~Arg] `keyword` Prod2
```
The two RHS above would have different "full" IDs (for backreferences say, from `Prod2`), but the same "simplified" ID (for forward references from SDOs) since things like constraints and optionality would be removed.

**Comment by michaelficarra** [comment]
@rbuckton I've updated this PR to just do the higher density digests. This should be uncontroversial now. For ecma262, we've decided to take on the responsibility of creating identifiers that meet our specific needs.

**Comment by rbuckton** [comment]
> [...] For ecma262, we've decided to take on the responsibility of creating identifiers that meet our specific needs.

That's unfortunate. I was about to push up a PR that adds a "simple" mode for `Resolver.getRightHandSideLinkId`. I was considering how best to support both ids when generating `ecmarkup` nodes during emit, since the RHS link id is currently in an `a` attribute of `emu-rhs`. I wasn't certain if emitting a preceding `<a name="{simpleLink}"></a>` would work for a link to an RHS in ecmarkup, or whether `emu-rhs` would need to be extended to support two ids.

**Comment by rbuckton** [comment]
> I wasn't certain if emitting a preceding `<a name="{simpleLink}"></a>` would work for a link to an RHS in ecmarkup, or whether `emu-rhs` would need to be extended to support two ids.

It's been too long since I looked at the emitter, that's already what I do :)

**Comment by rbuckton** [comment]
Rather, that's what I already do if `emitLinks: true` is passed to the grammar options. I'd probably still need another attribute in `emu-rhs` for the simple id.

**Review by rbuckton — APPROVED** [review]

**Comment by bakkot** [comment]
> That's unfortunate.

So it turned out that Ecmarkup actually has more complex needs than we'd realized at first. In particular, something like

```
FunctionExpression : `function` BindingIdentifier_opt `(` [etc]
```
can be "matched" by both
```
FunctionExpression : `function` BindingIdentifier `(` [etc]
```
and
```
FunctionExpression : `function` `(` [etc]
```

And there's no real way to go from that last case to the original definition: you have to actually walk all the definitions looking for a match. That means we need to rely on an explicit mapping, rather than mapping each thing to a "summary" which ignores unnecessary parts and allows us to match by comparing summaries.

**Comment by rbuckton** [comment]
That's fair. It does sound like an interesting problem I could solve in the `grammarkdown` API regardless (i.e., given a collapsed production, find the definition that matches).

**Comment by bakkot** [comment]
I'd be happy to have such an API! I've [implemented it myself](https://github.com/tc39/ecmarkup/blob/c6e3acc3fb8707997609980db78749a4c4aab44f/src/lint/utils.ts#L57) and would replace that with a call to grammarkdown were one available.

Though in this particular case that wouldn't have been sufficient on its own - we needed to be able to link the _generated HTML elements_ to each other, so we'd have to do some more work to track which HTML element was generated from which grammarkdown RHS. (For which purpose I ended up [reimplementing](https://github.com/tc39/ecmarkup/blob/c6e3acc3fb8707997609980db78749a4c4aab44f/src/Spec.ts#L1330) the `rhsMatches` algorithm linked above to operate on HTML elements.)

We didn't have this problem with the earlier approach because the `a` identifiers are put onto the generated HTML elements.

**Pull request merged**
