### PR TITLE
Escape text output in HTML Emitter

### PR DESCRIPTION
**Pull request by bterlson**

### CODE REVIEW

**Comment by rbuckton** [comment]
Is it really necessary to take an external dependency for something as simple as HTML entity escaping?

**Comment by rbuckton** [comment]
There's already an `encode` method on `Emitter` that does this:

```
    protected encode(text: string) {
        return text.replace(/[&<>'"]/g, ch => {
            switch (ch) {
                case "&": return "&amp;";
                case "<": return "&lt;";
                case ">": return "&gt;";
                case "'": return "&apos;";
                case '"': return "&quot;";
            }
        });
    }
```

**Comment by rbuckton** [comment]
I've fixed the missing encoding cases using existing functionality. Closing this PR.

**Comment by bterlson** [comment]
I'll convert you to substackianism one day :-P But for now, thanks a bunch!!

**Pull request closed without merging**
